app/src/main/java/com/pavitrawalia/calcify/MainActivity.java
i have removed the floating action button from the mainactiviy.java .
Fixes # 8
- Bug fix
=> remove the floating point action button

app/src/main/java/com/pavitrawalia/calcify/ui/general/GeneralFragment.java, app/src/main/res/drawable/ic_backspace_black_24dp.xml, app/src/main/res/layout/fragment_general.xml, app/src/main/res/values/colors.xml
1. Arithmetic Calculator with functionalities -> Fundamental Arithmetic,Exponential, Logarithmic & Trignometric
2. UI Improved 
Fixes # 6
Contributor: UtpalenduBarman
=> Create functionality for arithmetic operations #6

app/src/main/java/com/pavitrawalia/calcify/ui/general/GeneralFragment.java
Improvement in General Calculator Activity 
Fixes # 19
=> Improvement in General Calculator Activity

app/src/main/java/com/pavitrawalia/calcify/ui/unit_conversion/UnitConversionFragment.java, app/src/main/res/drawable/edbg.xml, app/src/main/res/drawable/edspinnerbg.xml, app/src/main/res/layout/fragment_unit_conversion.xml, app/src/main/res/navigation/mobile_navigation.xml, app/src/main/res/values/colors.xml
add ui for unit conversion 
Fixes #7 <br>
Contributor: Mahmoud Mabrok
[x] New feature
=> add ui for unit conversion

app/src/main/AndroidManifest.xml, app/src/main/java/com/pavitrawalia/calcify/ui/vat_gst_calculator/GstCalculator.java, app/src/main/java/com/pavitrawalia/calcify/ui/vat_gst_calculator/VatCalulator.java, app/src/main/java/com/pavitrawalia/calcify/ui/vat_gst_calculator/VatGstFragment.java, app/src/main/res/layout/activity_gst_calculator.xml, app/src/main/res/layout/activity_vat_calulator.xml, app/src/main/res/layout/fragment_vat_gst.xml, app/src/main/res/values/strings.xml
Added User Interface for VAT And GST Calculations 
Fixes Issue #22
=> Created User Interface for VAT And GST

.idea/misc.xml, app/build.gradle, app/src/main/java/com/pavitrawalia/calcify/ui/unit_conversion/Converter.java, app/src/main/java/com/pavitrawalia/calcify/ui/unit_conversion/IConverter.java, app/src/main/java/com/pavitrawalia/calcify/ui/unit_conversion/LengthCoverter.java, app/src/main/java/com/pavitrawalia/calcify/ui/unit_conversion/PressureCoverter.java, app/src/main/java/com/pavitrawalia/calcify/ui/unit_conversion/TemperatureCoverter.java, app/src/main/java/com/pavitrawalia/calcify/ui/unit_conversion/TimeCoverter.java, app/src/main/java/com/pavitrawalia/calcify/ui/unit_conversion/UnitConversionFragment.java, app/src/main/java/com/pavitrawalia/calcify/ui/unit_conversion/UnitUtils.java, app/src/main/java/com/pavitrawalia/calcify/ui/unit_conversion/WeightCoverter.java, app/src/main/res/layout/fragment_unit_conversion.xml, app/src/test/java/com/pavitrawalia/calcify/ui/unit_conversion/LengthCoverterTest.java, app/src/test/java/com/pavitrawalia/calcify/ui/unit_conversion/PressureCoverterTest.java, app/src/test/java/com/pavitrawalia/calcify/ui/unit_conversion/TemperatureCoverterTest.java, app/src/test/java/com/pavitrawalia/calcify/ui/unit_conversion/TimeCoverterTest.java, app/src/test/java/com/pavitrawalia/calcify/ui/unit_conversion/WeightCoverterTest.java
Added functionality for unit conversion.
Fixes #12 
Contributor: Mahmoud Mabrok
=> add logic for unit conversion

app/src/main/java/com/pavitrawalia/calcify/ui/vat_gst_calculator/GstCalculator.java, app/src/main/java/com/pavitrawalia/calcify/ui/vat_gst_calculator/VatCalulator.java, app/src/main/res/layout/activity_gst_calculator.xml, app/src/main/res/layout/activity_vat_calulator.xml
1. Functionality of GST Added
2. Functionality of VAT Added
Fixes # 23
=> Create functionality for VAT & GST Calculation

app/src/main/java/com/pavitrawalia/calcify/ui/gpa_calculator/GPAFragment.java, app/src/main/res/layout/fragment_gpa_calculator.xml
User Interface for GPA Calculator Created
Fixes # 21
=> Create UI for GPA Calculations

app/src/main/java/com/pavitrawalia/calcify/ui/gpa_calculator/GPAFragment.java, app/src/main/res/layout/fragment_gpa_calculator.xml
Create functionality for GPA Calculations 
Fixes # 33
=> Create functionality for GPA Calculations

README.md, app/build.gradle, app/src/main/java/com/pavitrawalia/calcify/ui/About_info/AboutInfoViewModel.java, app/src/main/java/com/pavitrawalia/calcify/ui/About_info/About_info.java, app/src/main/java/com/pavitrawalia/calcify/ui/Contact_us/ContactUsViewModel.java, app/src/main/java/com/pavitrawalia/calcify/ui/Contact_us/Contact_us.java, app/src/main/res/drawable/ic_contact_mail_black_24dp.xml, app/src/main/res/drawable/ic_info_black_24dp.xml, app/src/main/res/layout/about_info_fragment.xml, app/src/main/res/layout/contact_us_fragment.xml, app/src/main/res/menu/activity_main_drawer.xml, app/src/main/res/navigation/mobile_navigation.xml, app/src/main/res/values/strings.xml
I have added two categories(1.about/info 2.contact us) in navigation drawer and also made two corresponding fragments.
Fixes # 39 <br>
Please delete options that are not relevant.
=> Adding two more categories in the navigation drawer

app/src/main/res/layout/contact_us_fragment.xml
I have created this UI for Contact us Activity.
Fixes #53  <br>
=> UI for Contact us Activity

app/src/main/res/layout/about_info_fragment.xml, app/src/main/res/values/strings.xml
I have created this UI for About Info Activity.
Fixes #52  <br>
=> UI for About Info Activity

app/src/main/res/drawable/edbg.xml, app/src/main/res/drawable/edspinnerbg.xml, app/src/main/res/drawable/ic_swap_vert_black_24dp.xml, app/src/main/res/layout/fragment_unit_conversion.xml, app/src/main/res/values/colors.xml
UI Improvements in Unit Conversion Activity
Fixes #51 <br>
=> UI Improvements in Unit Conversion Activity

app/src/main/java/com/pavitrawalia/calcify/ui/unit_conversion/UnitConversionFragment.java
Add functionality to swap button in Unit Conversion Activity
Fixes #58 <br>
=> Add functionality to swap button in Unit Conversion Activity

app/src/main/res/layout/fragment_vat_gst.xml
Solved misaligned button in Vat and Gst Activity.
Fixes #49  <br>
=> Solved misaligned button in Vat and Gst Activity

app/src/main/java/com/pavitrawalia/calcify/ui/integral_differential_calculator/IntegralDifferentialFragment.java, app/src/main/res/layout/fragment_integral_differential.xml, app/src/main/res/layout/nav_toolbar.xml
Create UI for Integral & Differential Calculator 
Fixes # 32 <br>
( In case issue deals with UI Improvements)
=> Create UI for Integral & Differential Calculator

AndroidManifest.xml
Restricted Orientation to portrait mode.
Issue #63 <br>
Contributor: < Parjanya Aditya Shukla >
=> Restricted Orientation to Portrait mode

app/src/main/res/layout/fragment_gpa_calculator.xml, app/src/main/res/layout/fragment_vat_gst.xml, app/src/main/res/layout/nav_header_main.xml, app/src/main/res/values/strings.xml
Updating the navigation drawer header
Fixes # 65 <br>
( In case issue deals with UI Improvements)
=> Updating the navigation drawer header

app/src/main/res/layout/fragment_gpa_calculator.xml, app/src/main/res/layout/fragment_vat_gst.xml, app/src/main/res/layout/nav_header_main.xml, app/src/main/res/values/strings.xml
Please include a summary of the change and which issue is fixed.
Fixes # 67 <br>
Please delete options that are not relevant.
( In case issue deals with UI Improvements)
=> Improvements in VAT and GST Activity

app/src/main/res/layout/contact_us_fragment.xml
Misaligned elements in Contact Us Activity
Fixes # 66
Please delete options that are not relevant.
( In case issue deals with UI Improvements)
=> Misaligned elements in Contact Us Activity
